-- PostgreSQL-compatible schema for insurance dashboard

CREATE TABLE IF NOT EXISTS leads (
    id SERIAL PRIMARY KEY,
    meta_lead_id VARCHAR(255) UNIQUE,
    lead_form_id VARCHAR(255),
    source VARCHAR(50) DEFAULT 'facebook',
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    full_name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(20),
    company_name VARCHAR(255),
    job_title VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(2),
    country VARCHAR(255),
    zip_code VARCHAR(20),
    status VARCHAR(20) DEFAULT 'new',
    notes TEXT,
    signal VARCHAR(10) DEFAULT 'red',
    auto_premium INTEGER,
    home_premium INTEGER,
    tenant_premium INTEGER,
    custom_form_fields JSONB,
    raw_payload TEXT,
    meta_created_at TIMESTAMP,
    synced_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quotes (
    id SERIAL PRIMARY KEY,
    lead_id INTEGER,
    lead_name VARCHAR(255) NOT NULL,
    lead_email VARCHAR(255),
    lead_phone VARCHAR(20),
    meta_id VARCHAR(255),
    meta_source VARCHAR(100),
    potential_status VARCHAR(100),
    premium NUMERIC(10,2),
    renewal_date DATE,
    signal VARCHAR(10) DEFAULT 'red',
    status VARCHAR(20) DEFAULT 'draft',
    entry_mode VARCHAR(20),
    ownership VARCHAR(50),
    vehicle_use VARCHAR(50),
    annual_km INTEGER,
    winter_tires BOOLEAN,
    anti_theft BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quote_drivers (
    id SERIAL PRIMARY KEY,
    quote_id INTEGER REFERENCES quotes(id) ON DELETE CASCADE,
    driver_number INTEGER NOT NULL,
    relationship VARCHAR(50),
    dash_name VARCHAR(255),
    dash_dln VARCHAR(50),
    dash_dob DATE,
    dash_gender CHAR(1),
    dash_marital_status VARCHAR(50),
    dash_address TEXT,
    dash_years_licensed INTEGER,
    dash_years_continuous_insurance INTEGER,
    dash_years_claims_free INTEGER,
    dash_nonpay_3y INTEGER,
    dash_claims_6y INTEGER,
    dash_first_party_6y INTEGER,
    dash_dcpd_6y INTEGER,
    dash_current_company VARCHAR(255),
    dash_current_policy_expiry DATE,
    dash_current_vehicles_count INTEGER,
    dash_current_operators_count INTEGER,
    dash_first_insurance_date DATE,
    mvr_birth_date DATE,
    mvr_licence_expiry_date DATE,
    mvr_convictions_count INTEGER,
    mvr_convictions JSONB,
    mvr_issue_date DATE,
    g_date DATE,
    g1_date DATE,
    g2_date DATE,
    insufficient_experience BOOLEAN,
    dash_json TEXT,
    mvr_json TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quote_properties (
    id SERIAL PRIMARY KEY,
    quote_id INTEGER REFERENCES quotes(id) ON DELETE CASCADE,
    property_number INTEGER,
    property_address VARCHAR(255),
    property_city VARCHAR(255),
    property_postal VARCHAR(20),
    property_type VARCHAR(100),
    year_built INTEGER,
    storeys INTEGER,
    units INTEGER,
    families INTEGER,
    year_purchased INTEGER,
    owner_occupied BOOLEAN,
    inlaw_suite BOOLEAN,
    basement_apartment BOOLEAN,
    living_area_sqft INTEGER,
    basement_area_sqft INTEGER,
    basement_finished_percent INTEGER,
    electrical VARCHAR(100),
    plumbing VARCHAR(100),
    roofing VARCHAR(100),
    heating VARCHAR(100),
    full_baths INTEGER,
    half_baths INTEGER,
    burglar_alarm BOOLEAN,
    fire_alarm BOOLEAN,
    sprinkler_system BOOLEAN,
    smoke_detectors INTEGER,
    fire_extinguishers INTEGER,
    block_watch BOOLEAN,
    walled BOOLEAN,
    deadbolts BOOLEAN,
    property_json TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
